# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FyberOffer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FyberOffer
  pod 'CryptoSwift'
  pod 'SwiftyJSON'

  target 'FyberOfferTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'CryptoSwift'
    pod 'SwiftyJSON'
  end

  target 'FyberOfferUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
