# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OfferFramework' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OfferFramework
 pod 'CryptoSwift'
  pod 'SwiftyJSON'
  target 'OfferFrameworkTests' do
    inherit! :search_paths
    # Pods for testing
 pod 'CryptoSwift'
  pod 'SwiftyJSON'
  end

end
